### ISSUE TITLE
thumbnail metadata keyword & limit # of images returned

### ISSUE THREAD

**Issue by AliceYuan** [SAAVY/magpie#130]
"thumbnail" metatag pick the best image if there are multiple, do not put in an array
limit number of images returned with scraping body tags
remove tracking pixels when trying to scrape images (not sure how easy it is to do)

test url: https://www.apple.com/gifts/for-music-lovers/

**Comment by s-varun** [comment]
https://github.com/SAAVY/magpie/pull/136
