### ISSUE TITLE
Add Favicon to product website

### ISSUE THREAD

**Issue by adityatrivedi** [SAAVY/magpie#54]
The current product website does not have a Favicon.

<img width="255" alt="screen shot 2015-07-18 at 19 30 25" src="https://cloud.githubusercontent.com/assets/1791760/8763925/7828b012-2d83-11e5-8592-2f2d7c04377e.png">

**Comment by AliceYuan** [comment]
LOL @adityatrivedi  wrong repo :p

**Comment by AliceYuan** [comment]
https://github.com/SAAVY/projectmagpie.github.io

**Comment by adityatrivedi** [comment]
Oh my bad :(  I will close the issue here and open it on the website repo.
